export const SECTION_LOGO = 'SECTION_LOGO';
export const SECTION_GENESIS = 'SECTION_GENESIS';
export const SECTION_AGENDA = 'SECTION_AGENDA';
export const SECTION_MEMBERS = 'SECTION_MEMBERS';
export const SECTION_TEACHERS = 'SECTION_TEACHERS';
export const SECTION_MERCHANDISE = 'SECTION_MERCHANDISE';
export const SECTION_RESOURCES = 'SECTION_RESOURCES';
export const SECTION_ABOUT = 'SECTION_ABOUT';